language: python
python:
  - "3.6"
  
install:
  - pip install codeclimate-test-reporter
  - pip install coveralls
  
after_success:
  - coveralls
  - codeclimate-test-reporter
script:
    # Test install with current version of setuptools
  - pip install .
  - coverage run --source=pyrabbit setup.py test
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: always
    on_failure: always